name: notes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #network
  retrofit: 1.3.4+1
  json_annotation: 3.1.0
  dio: 3.0.10

  #bloc
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0

  #ui
  cupertino_icons: 1.0.0

  #utils
  uuid: 3.0.6

dev_dependencies:
  build_runner: 1.11.1

  #network_generators
  retrofit_generator: 1.4.1
  json_serializable: 3.5.1

flutter:
  uses-material-design: true